import { create } from "zustand";
import { persist } from "zustand/middleware";
import type { SkillTemplate } from "../schema/types";

interface SkillState {
  skills: SkillTemplate[];
  addSkill: (skill: SkillTemplate) => void;
  updateSkill: (id: string, patch: Partial<SkillTemplate>) => void;
  removeSkill: (id: string) => void;
  loadSkills: (skills: SkillTemplate[]) => void;
}

export function createDefaultSkill(id: string, name: string): SkillTemplate {
  return {
    id,
    name,
    kind: "active",
    system: "gathering",
    usableByInteractables: false,
    activityTags: [],
    abilityTags: [],
    baseDurationMs: 1400,
    baseEnergyCost: 10,
    basePower: 5,
    powerPerLevel: 1,
    baseXpToNext: 25,
    xpScaling: 1.18,
    barColor: "#555555",
    accentColor: "#777777",
    description: "",
    perkMilestones: [],
  };
}

const TREE_COLOR = "#415236";
const TREE_ACCENT = "#678752";

const SEED_SKILLS: SkillTemplate[] = [
  {
    id: "treecutting",
    name: "Treecutting",
    folder: "passive",
    kind: "passive",
    system: "gathering",
    activityTags: ["tree"],
    abilityTags: [],
    baseDurationMs: 0,
    baseEnergyCost: 0,
    basePower: 0,
    powerPerLevel: 0,
    baseXpToNext: 30,
    xpScaling: 1.18,
    barColor: TREE_COLOR,
    accentColor: TREE_ACCENT,
    description: "Passive efficiency for tree actions.",
  },
  {
    id: "upward_chop",
    name: "Upward Chop",
    folder: "active",
    kind: "active",
    system: "gathering",
    activityTags: ["tree"],
    abilityTags: ["chop"],
    linkedPassiveId: "treecutting",
    baseDurationMs: 2000,
    baseEnergyCost: 12,
    basePower: 5,
    powerPerLevel: 1,
    baseXpToNext: 25,
    xpScaling: 1.18,
    barColor: TREE_COLOR,
    accentColor: TREE_ACCENT,
    description: "Auto-cast opener for tree damage.",
    perkMilestones: [
      {
        level: 10,
        description: "Upward Chop has a chance to restore 3 energy on hit.",
      },
      {
        level: 25,
        description: "Upward Chop's cast time is reduced by 1s.",
      },
      {
        level: 40,
        description: "Upward Chop grants a stacking buff that gives you 1% Treecutting experience gain for 10s, stacking up to 10.",
      },
    ],
  },
  {
    id: "downward_chop",
    name: "Downward Chop",
    folder: "active",
    kind: "active",
    system: "gathering",
    activityTags: ["tree"],
    abilityTags: ["chop"],
    linkedPassiveId: "treecutting",
    baseDurationMs: 4000,
    baseEnergyCost: 15,
    basePower: 10,
    powerPerLevel: 2,
    baseXpToNext: 25,
    xpScaling: 1.18,
    barColor: TREE_COLOR,
    accentColor: TREE_ACCENT,
    description: "Unlocks at Treecutting Lv 3. Bonus arms after 3 successful Upward Chops.",
    unlockCondition: 'skill("treecutting").level >= 3',
  },
  {
    id: "side_chop",
    name: "Side Chop",
    folder: "active",
    kind: "active",
    system: "gathering",
    activityTags: ["tree"],
    abilityTags: ["chop"],
    linkedPassiveId: "treecutting",
    baseDurationMs: 1000,
    baseEnergyCost: 11,
    basePower: 7,
    powerPerLevel: 1,
    baseXpToNext: 25,
    xpScaling: 1.18,
    barColor: TREE_COLOR,
    accentColor: TREE_ACCENT,
    description: "Unlocks at Treecutting Lv 5.",
    unlockCondition: 'skill("treecutting").level >= 5',
  },
  {
    id: "rat_swipe",
    name: "Swipe",
    folder: "combat",
    kind: "active",
    system: "combat",
    usableByInteractables: true,
    combatSchool: "chaos",
    activityTags: ["enemy", "friendly"],
    abilityTags: [],
    baseDurationMs: 2000,
    baseEnergyCost: 0,
    basePower: 4,
    powerPerLevel: 0,
    unlockCondition: "false",
    baseXpToNext: 25,
    xpScaling: 1.18,
    barColor: "#A72727",
    accentColor: "#A72727",
    description: "A desperate lunge that claws at the target.",
    bioboardSubcategory: "Vermin",
    bioboardPrimaryText: "Lunges and swipes at the target.",
    usageProfile: {
      castMode: "cast",
      interruptible: false,
      hitCount: 1,
      maxTargets: 1,
      targetPattern: "single",
      usageContext: "combat",
    },
    effects: [
      {
        id: "swipe_damage",
        trigger: "on_cast_complete",
        target: "target",
        type: "damage",
      },
    ],
  },
  {
    id: "companion_strike",
    name: "Companion Strike",
    folder: "combat",
    kind: "active",
    system: "combat",
    usableByInteractables: true,
    combatSchool: "genesis",
    activityTags: ["enemy"],
    abilityTags: [],
    baseDurationMs: 1800,
    baseEnergyCost: 0,
    basePower: 3,
    powerPerLevel: 0,
    unlockCondition: "false",
    baseXpToNext: 25,
    xpScaling: 1.18,
    barColor: "#4F6D8A",
    accentColor: "#82B2D8",
    description: "A simple attack companions can use against hostile targets.",
    bioboardSubcategory: "Companion",
    bioboardPrimaryText: "A quick allied strike against a hostile target.",
    usageProfile: {
      castMode: "cast",
      interruptible: false,
      hitCount: 1,
      maxTargets: 1,
      targetPattern: "single",
      usageContext: "combat",
    },
    effects: [
      {
        id: "companion_strike_damage",
        trigger: "on_cast_complete",
        target: "target",
        type: "damage",
      },
    ],
  },
  {
    id: "telekinetic_slam",
    name: "Telekinetic Slam",
    folder: "combat",
    kind: "active",
    system: "combat",
    usableByInteractables: true,
    combatSchool: "string",
    image: "",
    baseManaCost: 8,
    bioboardSubcategory: "Gravity Manipulation",
    bioboardPrimaryText: "Deals 30-50 String Damage",
    bioboardSecondaryText: 'If the target has the status, "Suspend", it deals 200% more damage.',
    activityTags: ["enemy"],
    abilityTags: [],
    baseDurationMs: 4000,
    baseEnergyCost: 12,
    basePower: 0,
    powerPerLevel: 0,
    unlockCondition: "false",
    baseXpToNext: 25,
    xpScaling: 1.18,
    barColor: "#555555",
    accentColor: "#777777",
    description: "A focused telekinetic strike that crushes the target.",
    usageProfile: {
      castMode: "cast",
      interruptible: false,
      hitCount: 1,
      maxTargets: 1,
      targetPattern: "single",
      usageContext: "combat",
    },
    effects: [
      {
        id: "slam_damage",
        trigger: "on_cast_complete",
        target: "target",
        type: "damage",
        customText: "Large direct String damage.",
      },
    ],
    statusInteractions: [
      {
        id: "slam_vs_suspended",
        condition: 'target.has_effect("suspended")',
        consumeStatusEffectId: "suspended",
        consumeStatusTarget: "target",
        powerMultiplier: 3,
        note: "Consumes Suspended and deals 200% more damage.",
      },
    ],
  },
  {
    id: "suspend",
    name: "Suspend",
    folder: "combat",
    kind: "active",
    system: "combat",
    usableByInteractables: true,
    combatSchool: "string",
    image: "",
    baseManaCost: 4,
    bioboardSubcategory: "Gravity Manipulation",
    bioboardPrimaryText: "Applies Suspended to the target",
    bioboardSecondaryText: "Suspends the target for follow-up abilities.",
    activityTags: ["enemy"],
    abilityTags: [],
    baseDurationMs: 2000,
    baseEnergyCost: 14,
    basePower: 0,
    powerPerLevel: 0,
    unlockCondition: "false",
    baseXpToNext: 25,
    xpScaling: 1.18,
    barColor: "#555555",
    accentColor: "#777777",
    description: "Lifts the target into the air, applying Suspended.",
    usageProfile: {
      castMode: "cast",
      interruptible: false,
      hitCount: 1,
      maxTargets: 1,
      targetPattern: "single",
      usageContext: "combat",
    },
    effects: [
      {
        id: "suspend_control",
        trigger: "on_cast_complete",
        target: "target",
        type: "apply_status",
        statusEffectId: "suspended",
        durationMs: 6000,
        customText: "Applies Suspended to the target.",
      },
    ],
    statusInteractions: [
      {
        id: "apply_suspended",
        applyStatusEffectId: "suspended",
        applyStatusTarget: "target",
        note: "Applies Suspended to the target.",
      },
    ],
  },
  {
    id: "sand_salvo",
    name: "Sand Salvo",
    folder: "combat",
    kind: "active",
    system: "combat",
    usableByInteractables: true,
    combatSchool: "string",
    image: "",
    baseManaCost: 5,
    bioboardSubcategory: "Gravity Manipulation",
    bioboardPrimaryText: "Deals repeated String damage",
    bioboardSecondaryText: "If the target is Suspended, consume it and apply Armor Shredded.",
    activityTags: ["enemy"],
    abilityTags: [],
    baseDurationMs: 3000,
    baseEnergyCost: 16,
    basePower: 0,
    powerPerLevel: 0,
    unlockCondition: "false",
    baseXpToNext: 25,
    xpScaling: 1.18,
    barColor: "#555555",
    accentColor: "#777777",
    description: "A barrage of suspended grit that tears through the target.",
    usageProfile: {
      castMode: "channel",
      interruptible: false,
      hitCount: 5,
      castTickIntervalMs: 600,
      maxTargets: 1,
      targetPattern: "single",
      usageContext: "combat",
    },
    effects: [
      {
        id: "salvo_damage",
        trigger: "on_tick",
        target: "target",
        type: "damage",
        hitCount: 5,
        customText: "Five-hit arcane missile style barrage.",
      },
    ],
    statusInteractions: [
      {
        id: "salvo_vs_suspended",
        condition: 'target.has_effect("suspended")',
        consumeStatusEffectId: "suspended",
        consumeStatusTarget: "target",
        applyStatusEffectId: "armor_shredded",
        applyStatusTarget: "target",
        note: "Consumes Suspended and applies Armor Shredded.",
      },
    ],
  },
];

export const useSkillStore = create<SkillState>()(
  persist(
    (set) => ({
      skills: SEED_SKILLS,

      addSkill: (skill) =>
        set((s) => ({ skills: [...s.skills, skill] })),

      updateSkill: (id, patch) =>
        set((s) => ({
          skills: s.skills.map((sk) => (sk.id === id ? { ...sk, ...patch } : sk)),
        })),

      removeSkill: (id) =>
        set((s) => ({ skills: s.skills.filter((sk) => sk.id !== id) })),

      loadSkills: (skills) => set({ skills }),
    }),
    {
      name: "editor-skills",
      partialize: (state) => ({ skills: state.skills }),
    }
  )
);
